#!/usr/bin/env bash

# Check if all required arguments have been provided
if [ "$#" -lt 4 ]; then
		echo "Usage: transfer_file.sh <path_to_file> <ip_address> <username> <path_to_ssh_key>"
			exit 1
fi

# Assign the arguments to more descriptive variables
local_path="$1"
remote_ip="$2"
remote_user="$3"
ssh_key="$4"

# Copy the file to the remote server using SCP
scp -i "$ssh_key" -o StrictHostKeyChecking=no "$local_path" "$remote_user@$remote_ip":~/.

# Check if the file transfer was successful
if [ $? -eq 0 ]; then
		echo "File transfer successful!"
	else
			echo "File transfer failed."
fi

