#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to redirect /redirect_me to a new page

sudo apt-get update
sudo apt-get install -y nginx

echo '<html><head><meta http-equiv="refresh" content="0;url=https://www.example.com" /></head></html>' | sudo tee /var/www/html/redirect_me.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.example.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart

