#!/usr/bin/env bash
# Set up Nginx to include a custom HTTP header in its response (on web-01 and web-02)
# The name of the custom HTTP header should be X-Served-By
# The value of the custom HTTP header should display the hostname of the server that Nginx is running on
sudo apt-get update
sudo apt-get -y install nginx

# Configure the firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# Adjust permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# Create an index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a 404 error page
echo "This is not the page you are looking for" | sudo tee /var/www/html/404.html

# Code to configure a redirect for a specific page (/redirect_me) and add the custom header to display the hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.example.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Code to configure a redirect for the 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the web server after updating the settings
sudo service nginx restart

