#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configures HAProxy to send traffic to web-01 and web-02 servers
# Distributes requests using a round-robin algorithm
# Makes sure that HAProxy can be managed via an init script

# Update package repositories
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
server_config=\
"
frontend myfrontend
        bind *:80
        mode http
        default_backend mybackend
backend mybackend
        balance roundrobin
        server web01 100.25.19.204:80 check
        server web02 54.157.159.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
