#!/usr/bin/env bash
# debugging nginx port 80
# Solution: Replace the default Nginx config with a copy of the available config using a symbolic link
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart the Nginx service to apply the configuration changes
service nginx restart
# Forcefully terminate any remaining Nginx processes to ensure a clean start
pkill -9 nginx

