#!/usr/bin/env bash
# Bash scripts that display best school 10 times
counter=1

while [ $counter -le 10 ]
do
	  if [ $counter -eq 9 ]
		    then
			        echo "Best School"
				    echo "Hi"
				      else
					          echo "Best School"
						    fi
						      counter=$((counter + 1))
					      done
