#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes

hour=0
while [ $hour -lt 12 ]
do
  minute=0
  while [ $minute -lt 60 ]
  do
    echo "Hour: $hour"
    echo $minute
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done
