#!/usr/bin/env bash
# A bash script that configure an ubuntu server
sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
