#!/usr/bin/env bash

# backup original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# set localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# add facebook.com to resolve to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
