#!/usr/bin/env bash
# This code Fixes a web server to run Nginx as the nginx user listening on port 8080.

# Set a user in the config by replacing '#user' and its value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Then Replace port 80 with 8080 in the sites-available config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# After that give read and write permissions to the owner of the config file
chmod 644 /etc/nginx/nginx.conf
# Check if Apache is running and kill the process if it is
pkill apache2
# Start the Nginx service with the new nginx user
sudo -u nginx service nginx start
