#!/usr/bin/env bash
# Set Nginx to run as the 'nginx' user and listen on port 8080.
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# Change the default port to 8080 in the site config.
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# Set file permissions for the nginx config.
chmod 644 /etc/nginx/nginx.conf
# Kill any running Apache processes to avoid interference with Nginx.
pkill apache2
# Start the Nginx service as the 'nginx' user.
sudo -u nginx service nginx start

